name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  main:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: ~1.17
      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.42.0
      - name: Test
        run: go test -count=1 -v ./...
